from repository.admin_property_list import Admin_property_list_repository
from starlette.responses import StreamingResponse

class Admin_property_list_service:

        def __init__(self, db, Admin_property_list_repository):
            self.db = db
            self.base_query = Admin_property_list_repository.base_query

        def apply_conditions(self, q: str | None, city: str | None, category: int | None, has_been_paid: int | None):
            conditions, params = Admin_property_list_repository.build_property_filters(q, city, category, has_been_paid)
            base_query = self.base_query
            if conditions:
                base_query += " AND " + " AND ".join(conditions)
            return self.db.execute(base_query, tuple(params), fetchall=True)
        
        def export_properties_csv(self, rows, admin_id: int, q: str | None, city: str | None, category: int | None, has_been_paid: int | None):
            import csv
            import io
            output = io.StringIO()
            writer = csv.writer(output)
            writer.writerow(["# Property export"])
            writer.writerow([f"# Generated by admin_id: {admin_id}"])
            writer.writerow([f"# Filters: q={q}, city={city}, category={category}, paid={has_been_paid}"])
            writer.writerow([])  # blank line for readability

            writer.writerow(["property_id", "digital_address", "city", "monthly_bill", "billing_date", "has_been_paid"])
            for row in rows:
                writer.writerow(row)
            
            output.seek(0)
            return StreamingResponse(output, media_type="text/csv", headers={"Content-Disposition": "attachment; filename=properties.csv"})